<?php
session_start();
?>

<!DOCTYPE html>

<html lang="fr">

	<head>
		<meta charset="utf-8">
		<title>Courseland - Vente de cours en ligne</title>
		<link href="../feuilles_style/mentions_legales_style.css" rel="stylesheet">
		<link href="../feuilles_style/footer_style.css" rel="stylesheet">
		<link href="../feuilles_style/header_style.css" rel="stylesheet">
		<script src="http://code.jquery.com/jquery.js" type="text/javascript"></script>
		<script src="../menu_deroulant.js" type="text/javascript"></script>
	</head>
	
	<body>
		<div id="bloc_page">
		
			<?php include("header.php"); ?>
			
			<?php include("header_bis.php"); ?>
			
			<section>
				<article>
					<h1>Mentions légales concernant notre site</h1>
					
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae odio tortor. Fusce viverra, augue suscipit maximus placerat, ligula odio lobortis sem, id vulputate ex ante sit amet odio. Ut et ullamcorper erat. Vivamus at fermentum eros, vitae condimentum libero. Vestibulum sagittis tellus sit amet ante egestas pretium. Donec porta ipsum neque, eu volutpat elit lacinia rutrum. Donec rhoncus diam ut arcu molestie, et aliquet massa condimentum. Proin nunc arcu, fringilla in quam ut, blandit imperdiet elit. Suspendisse pretium placerat ligula, non molestie nibh suscipit vel.</p>
					
					<p>Suspendisse ultrices mi pulvinar, posuere odio quis, vestibulum purus. Phasellus laoreet ut lacus et venenatis. Suspendisse sed varius magna, vel lobortis velit. Pellentesque non ultrices ligula. Nunc lectus quam, vehicula vitae lorem eleifend, eleifend suscipit tortor. Aenean nulla arcu, commodo eu odio eu, suscipit bibendum metus. Ut vitae purus in massa efficitur facilisis. Mauris ultrices turpis fermentum justo ultrices, id tempor nisl condimentum.</p>
					
					<p>Vivamus pellentesque sollicitudin quam, sed iaculis neque finibus ut. Mauris volutpat purus ex, sit amet pharetra augue euismod vel. Vivamus pellentesque, neque a rhoncus sagittis, tortor nulla dignissim dui, id viverra nulla neque a purus. Phasellus ut sollicitudin felis. Curabitur id diam in neque tincidunt vulputate. Nulla posuere porttitor diam id scelerisque. Maecenas pharetra cursus magna, eu mollis augue. Vivamus at odio id felis aliquam posuere. Sed at ex non ex condimentum posuere sit amet at erat. Maecenas vel risus felis.</p>
					
					<p>Fusce viverra orci id dolor pulvinar, ut aliquam erat auctor. Morbi in malesuada ligula, ac tincidunt libero. Nullam luctus at augue nec maximus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam posuere sollicitudin neque, sit amet vulputate tellus cursus ut. Nulla facilisi. Vestibulum mauris ipsum, convallis vel laoreet id, consequat et dui.</p>
					
					<p>Vivamus ullamcorper magna sed felis consequat tempor. Aenean egestas interdum sem eget imperdiet. Integer faucibus a leo a dignissim. Nullam viverra, neque vel fringilla tempor, purus arcu consequat turpis, nec aliquam dolor erat pulvinar ex. Morbi venenatis at nulla vitae accumsan. Integer id lorem at risus lacinia vestibulum nec sed nisl. Suspendisse tempor augue ut felis interdum, et finibus enim viverra. Aenean vestibulum pretium purus sit amet maximus. Duis posuere enim vel facilisis convallis. In in arcu ex. In non commodo quam. Maecenas malesuada lacus eget elit dignissim cursus. Sed et ante non tortor suscipit sagittis. Nulla eget cursus ex.</p>
					
					<p>Nunc pellentesque libero vel urna sollicitudin iaculis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed leo ligula, egestas in tincidunt sit amet, rhoncus eget mauris. Mauris lacinia turpis convallis, imperdiet diam eu, vestibulum sapien. Donec ac consectetur dui. Duis neque nibh, semper id scelerisque vel, tincidunt id risus. Praesent quis congue ipsum, vel varius dui. Vivamus pharetra turpis a neque fringilla iaculis. Suspendisse convallis elementum ligula quis molestie. Suspendisse ultrices accumsan urna in interdum. Maecenas pretium varius sapien id sollicitudin. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce eget sapien vitae lacus cursus tincidunt id sed lorem. Nulla eget congue nulla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
					
					<p>Curabitur tempor dolor ut eros ullamcorper condimentum. Praesent sollicitudin rhoncus tortor, eget condimentum elit. Nulla aliquam quis lorem eget finibus. Nulla consectetur orci ac lectus efficitur aliquam. Ut auctor turpis neque, ut porttitor leo ultrices eget. Mauris pharetra molestie massa, vitae iaculis lorem. Suspendisse facilisis molestie dui, eget consectetur risus ornare ut. Sed porta turpis in malesuada suscipit. Ut convallis hendrerit mauris, eget pulvinar libero lacinia sed. Phasellus a mi vitae nulla rhoncus laoreet. Vestibulum sed dui vitae purus finibus porttitor venenatis id urna. Nam eu fermentum mauris. Quisque tincidunt venenatis iaculis. Cras sagittis a arcu sit amet venenatis.</p>
					
					<p>Etiam metus metus, laoreet vel commodo non, convallis nec arcu. Donec luctus pellentesque ligula, eget consectetur ante elementum ut. Donec mattis felis vitae dapibus tristique. Nulla blandit eu dolor at facilisis. Cras sollicitudin, dui id faucibus fermentum, dui justo iaculis felis, in auctor nulla ipsum quis felis. Maecenas quis justo nunc. Nulla rutrum venenatis sapien, vitae sollicitudin dui accumsan vehicula. In vitae vulputate sapien. Nullam sed purus sem. Integer a mauris libero.
					Proin non consectetur velit. Fusce tristique libero vestibulum nulla faucibus volutpat. Praesent eu orci nec mauris ullamcorper bibendum. Vivamus facilisis, ipsum eget porttitor rutrum, velit odio fermentum libero, id viverra libero quam vel magna. Vestibulum ac sapien sed arcu ultricies varius sed ac nisl. Maecenas in dui ut turpis imperdiet vestibulum at pretium risus. Praesent ut hendrerit justo. Sed at viverra velit, id accumsan eros. Vivamus et quam nec diam dictum pulvinar non a odio. Suspendisse pellentesque eros non aliquet venenatis. Fusce lobortis nibh eu tellus elementum, sit amet feugiat arcu auctor.</p>
					
					<p>Nullam id eros nulla. Fusce massa libero, pretium nec ullamcorper at, elementum nec mauris. Proin vitae libero scelerisque, ultricies libero pulvinar, hendrerit sem. Etiam fringilla lacus sed odio condimentum, vitae accumsan libero aliquet. Proin non pulvinar leo. Duis maximus purus vitae mi tempus, sed dapibus enim ullamcorper. Nullam accumsan nunc sit amet nibh consectetur ultrices. Sed eu libero tincidunt, malesuada lacus placerat, elementum tortor. Mauris malesuada sapien tortor, quis iaculis ex auctor ac. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc finibus lectus ex, sed aliquam libero hendrerit vitae. Praesent ac elit lorem. Aenean congue, neque id egestas tempor, orci lectus venenatis lorem, quis molestie libero metus vel risus. Fusce eu erat eu ipsum congue suscipit. Curabitur turpis purus, fermentum eget ex non, tincidunt laoreet urna.
					Mauris eu bibendum libero. Nulla lacinia sem velit, sit amet sollicitudin nisi cursus eget. Nulla mollis eu metus a porttitor. Maecenas mattis diam sed justo sagittis viverra. Maecenas hendrerit molestie euismod. Pellentesque placerat viverra orci in iaculis. Pellentesque sagittis et tellus sed pulvinar. Pellentesque consectetur sed mauris et dictum. Ut consequat mi dolor, ac ultricies tortor tempor quis. Aenean eget orci ex. Nunc mollis condimentum ipsum in egestas. Suspendisse euismod, nulla quis dictum posuere, ex odio semper nunc, a faucibus turpis ex id nunc. Duis commodo diam sed leo eleifend dignissim. Vestibulum ante sem, vulputate ac vulputate vitae, bibendum in nisl.</p>
					
					<p>Donec id tellus ut lorem rhoncus pulvinar. Quisque sed nisi rhoncus, commodo tellus vel, viverra turpis. Etiam ac scelerisque enim, quis laoreet dolor. Fusce a velit lobortis, porta magna eu, euismod felis. Morbi dui felis, placerat sed dictum ac, placerat ut libero. Phasellus bibendum ex nec erat aliquam, in luctus ipsum consectetur. Sed a purus in nibh pulvinar rhoncus et et nisi. Mauris at erat at nisi efficitur varius vitae a lorem. Vivamus et elementum eros. Etiam a nibh tempus, ultricies nisl ac, ultricies tortor. Nunc diam ex, rhoncus ut placerat sed, porta nec mauris.
					Phasellus vulputate, massa a dictum congue, urna tellus pretium lorem, nec ornare mi quam id lectus. Phasellus ligula felis, facilisis non tellus vel, molestie pharetra leo. Aliquam sollicitudin nunc a quam aliquam, in dapibus leo sagittis. Nam tempus hendrerit feugiat. Cras dolor erat, dictum vel dui eu, feugiat iaculis justo. Sed quis dolor eu purus tempus elementum ut vel nisi. Aliquam id facilisis sem, ac blandit dui. Morbi laoreet elit ut leo viverra varius ut id est. Praesent leo magna, vehicula eu odio eget, ultrices auctor mauris.
					Nulla facilisi. Mauris sed neque interdum turpis feugiat porta. Nunc eget sodales metus. Nulla a felis at lectus lacinia dapibus eget sed urna. Vivamus sapien magna, tempus non nisl vel, suscipit posuere lorem. Etiam auctor vel est in efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris non diam justo.
					Nullam venenatis lobortis risus, nec vehicula ligula. Sed egestas feugiat ullamcorper. Suspendisse potenti. Nulla in accumsan lacus. In eu ornare nisl, a euismod neque. Curabitur cursus ornare enim, at sagittis dolor lobortis sed. Morbi lacinia turpis id mauris condimentum volutpat.
					Etiam nec est lorem. Sed euismod felis eget ex suscipit eleifend. Vestibulum auctor vulputate sapien, in vestibulum dolor aliquet ut. Duis pharetra justo non metus venenatis volutpat ut nec nisl. Nunc ac mi vitae arcu imperdiet accumsan. Praesent risus lectus, aliquam sit amet tincidunt in, pharetra tempus arcu. Sed sit amet arcu libero. Quisque at quam id orci consectetur lobortis in in purus. Vestibulum vel felis suscipit, porta quam et, blandit orci. Quisque nibh felis, dapibus ac risus vel, efficitur molestie nisi. Etiam suscipit neque vel justo fringilla, a fermentum massa placerat. Aliquam urna velit, pulvinar vitae eros a, scelerisque interdum sapien. Mauris accumsan, ex at ultricies lobortis, elit erat lobortis enim, non vulputate nisl lacus eu metus.</p>
					
					<p>Maecenas urna sem, congue id ullamcorper tempor, laoreet et sapien. Quisque id egestas erat. Etiam sagittis est in urna luctus fringilla. Mauris elementum et leo id dignissim. Proin vel ligula sem. Nulla sit amet eros ut enim facilisis congue. Proin a porttitor massa. Fusce luctus nec quam sit amet dictum. Aliquam mollis velit vel erat rhoncus, at dapibus lectus viverra. Sed in est vel ante scelerisque tincidunt et at enim.
					Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec vitae urna pharetra, pharetra massa non, blandit risus. Duis odio purus, vehicula eget ligula sed, eleifend fermentum justo. Sed id lectus consectetur, dapibus felis interdum, finibus urna. Quisque pharetra molestie libero id varius. Nullam cursus velit non aliquam cursus. Ut in risus at massa ultrices pulvinar id at ligula. Pellentesque eu lacinia nulla. Vestibulum ac molestie lorem.
					In velit diam, tincidunt nec sapien nec, laoreet eleifend elit. Etiam viverra orci leo. Nunc vel volutpat nulla. Duis eu felis non tortor condimentum ornare. Mauris porta ultricies tortor vel dignissim. Pellentesque elementum enim dolor, in vehicula elit imperdiet eu. Suspendisse interdum nisi nec pretium posuere. Integer cursus arcu nec luctus fringilla. Quisque malesuada vulputate tellus sed tincidunt.
					Nam consequat risus quis est pellentesque posuere. Duis augue nisi, tempus in ipsum a, laoreet pellentesque arcu. Praesent blandit odio purus, at porttitor odio accumsan ac. Mauris vitae facilisis justo. Duis et diam quam. Duis fringilla arcu ac nulla convallis vulputate. Morbi sem ex, venenatis ut massa ut, tempor blandit lacus. Donec purus leo, varius nec augue id, tincidunt malesuada ipsum. Praesent porttitor lectus nec massa varius elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed vel nunc a dolor feugiat sodales.
					Nam eu enim libero. Suspendisse et euismod felis. Vivamus posuere eros quis enim efficitur tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque ullamcorper vel tellus id tristique. Sed malesuada feugiat erat, eu suscipit urna. Maecenas id tempus lacus, et porttitor augue. Nulla auctor urna non mauris porta sollicitudin. Nam dictum, ligula quis lobortis accumsan, enim libero tristique nulla, sit amet laoreet lectus risus at neque. Sed scelerisque tellus et nisl egestas commodo. Vivamus nec justo non risus tincidunt sodales ac vitae mi. Curabitur fringilla euismod gravida. Phasellus pulvinar enim vel tellus mollis, sed porttitor orci semper. Maecenas vulputate quam ante, quis sollicitudin mi lacinia vel.</p>
					
					<p>Phasellus placerat cursus suscipit. Curabitur hendrerit dapibus ex sit amet tincidunt. Maecenas at ligula sed quam molestie euismod. Sed eget ullamcorper turpis, sit amet iaculis leo. Suspendisse potenti. Sed justo arcu, gravida a eleifend elementum, hendrerit interdum dolor. Duis commodo ligula purus, a varius augue tristique et. Proin rutrum ligula ex, gravida lacinia eros ullamcorper id. Donec vel lacinia justo. Fusce lobortis ante convallis enim dictum, at scelerisque sem laoreet. Mauris pharetra, felis vel facilisis porttitor, quam turpis consectetur nisl, sed interdum sem nibh et turpis. Phasellus egestas erat ut porttitor molestie. Integer malesuada semper ligula quis fringilla. Proin tincidunt id tellus pellentesque dignissim.
					Pellentesque nec est felis. Vestibulum ut est vel urna pulvinar consectetur eu eu velit. Aliquam quis nulla sem. Vivamus eu aliquet nisi. Phasellus tristique lectus in ex vehicula, pretium cursus dolor sollicitudin. Morbi at accumsan elit. Vivamus ac pulvinar est, consequat fermentum ipsum. Curabitur accumsan leo justo, sed finibus libero imperdiet eu. Phasellus imperdiet sapien odio, sit amet placerat nibh maximus at. Integer risus nibh, bibendum a eros ut, laoreet consectetur sapien. Fusce efficitur fringilla elit id fermentum.</p>
					
					<p>Vivamus lectus ex, tempor eu maximus sed, gravida venenatis leo. Vestibulum vulputate mauris et nibh efficitur, at pretium eros commodo. In lacinia, orci cursus mattis rutrum, eros sem condimentum leo, id consectetur tellus arcu gravida augue. Mauris in nisl quis leo pharetra lobortis quis a mi. Nunc vel nisi nulla. Integer fringilla eget arcu at interdum. Phasellus viverra porta sagittis. Duis ultricies mollis nisi in ultrices. Morbi blandit dictum ipsum id consectetur. Nam id dui ut dui sollicitudin ultricies vel in urna. Maecenas ut tellus imperdiet, aliquet risus eu, dapibus nisl. Duis vel nunc sit amet enim lobortis cursus. Mauris scelerisque massa nec elit tempus laoreet. Curabitur pharetra vulputate nulla, in fermentum leo gravida quis. Donec iaculis nunc sed sem dapibus porta.
					Aliquam vitae feugiat odio, ac egestas dui. Fusce sodales enim sit amet mauris iaculis, ut congue velit vestibulum. Suspendisse orci lacus, fermentum et erat nec, imperdiet facilisis lorem. In ultrices rhoncus felis vitae cursus. Aenean ultricies dignissim consequat. Integer tristique erat vitae odio ullamcorper, a bibendum enim hendrerit. Sed massa tortor, malesuada nec purus quis, viverra tincidunt elit. Sed convallis metus erat, non pharetra enim euismod lobortis. Praesent bibendum, nisi nec vehicula mattis, sapien dolor egestas nisl, vel commodo libero neque nec est.
					Aliquam sagittis porta turpis, id placerat nunc blandit at. Vestibulum tincidunt arcu ut tortor varius commodo. Nam eu lectus non sapien semper molestie sit amet et ante. Nulla facilisis tortor nec ipsum aliquam elementum. Aenean mattis convallis efficitur. In mattis ultrices metus dictum volutpat. Nam ac turpis in risus dignissim convallis at non arcu. Nam in ex justo. Pellentesque molestie porttitor lorem, eu tristique lacus. Vivamus augue est, pharetra vel purus a, lobortis consequat quam.
					Curabitur porta cursus justo, et aliquet leo fringilla et. Quisque tristique urna eu sollicitudin iaculis. Vestibulum molestie vitae erat sed hendrerit. Vivamus congue, arcu sed luctus scelerisque, elit justo vestibulum magna, sed fringilla sapien nibh nec ante. Nulla lorem tortor, facilisis congue ipsum sit amet, sodales interdum odio. Mauris lacinia fringilla nisi pretium hendrerit. Sed gravida libero turpis, et lacinia arcu accumsan quis. Etiam consequat turpis non ante dignissim pulvinar. Nullam vestibulum lorem non fringilla posuere. Phasellus dictum ac ex sed scelerisque. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
					
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras dignissim sapien id elit mollis rutrum. Vestibulum nec volutpat lectus. Phasellus aliquet semper interdum. Ut sodales justo sed nisl ornare, ut pellentesque velit finibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla accumsan aliquam nibh, eu lobortis nisl mattis tincidunt. Nam mollis purus in sapien aliquam, ac porttitor felis faucibus. Fusce ornare mi non dictum porttitor. In hac habitasse platea dictumst.
					Ut est est, viverra at rhoncus in, consectetur et lorem. Maecenas facilisis dui et lacus ullamcorper consectetur. Sed interdum bibendum varius. Quisque cursus sed sapien ut efficitur. Phasellus quis cursus turpis. Donec condimentum arcu vel gravida aliquet. Nullam quam nunc, consequat ac diam at, malesuada viverra nisl. Cras tincidunt sagittis neque, quis condimentum lectus sollicitudin nec. Nulla porttitor, leo id volutpat luctus, lorem lorem dictum magna, ut aliquet lacus augue non nunc. Aliquam sed enim massa. Sed sed eros sit amet nisl cursus commodo nec nec eros. Cras massa ipsum, ultricies nec metus in, euismod egestas ante. Aenean ac finibus mi, in dignissim dolor.
					Nam ac dictum purus, pharetra lacinia mi. Pellentesque metus magna, iaculis in ante eu, dapibus placerat quam. Vestibulum erat felis, blandit vitae dolor eget, euismod tempor turpis. Vestibulum et elit feugiat, porta dui eget, varius dui. Cras at sollicitudin tellus. Duis id ornare sem, quis ultrices orci. Sed commodo, dui quis pellentesque ullamcorper, nisl felis varius ante, ut gravida ante mauris et dui. Suspendisse potenti. Integer nibh purus, euismod ut dui non, venenatis rhoncus tellus. Etiam lobortis interdum ligula. Mauris sollicitudin, mauris ac aliquam vulputate, risus neque malesuada leo, a laoreet dui risus laoreet lacus. Aliquam malesuada enim metus, sagittis efficitur nibh porta eu. Mauris ultrices lorem vitae semper iaculis. Sed sodales lobortis mi ut scelerisque. Phasellus elementum enim vitae nisl consectetur, nec facilisis elit pellentesque.</p>
					
					<p>Cras porta sagittis tempor. Mauris nec lectus ut purus cursus finibus ut ut nibh. Aliquam a lectus condimentum, vestibulum metus vitae, consequat justo. Nulla facilisis nisl in vestibulum malesuada. Nunc finibus enim in iaculis ultrices. Integer porta nibh et turpis tincidunt, ut scelerisque justo mattis. Morbi nec mi eros. Duis elementum interdum orci.
					Donec eget ornare lorem. Phasellus ac eros justo. Aliquam sed ornare tortor, non luctus dui. Suspendisse sed condimentum ante. Donec maximus malesuada eleifend. Phasellus at nulla ut est viverra convallis. Duis scelerisque egestas eros eget porttitor. In dictum scelerisque sem vel condimentum. Mauris ante sapien, pellentesque vel magna et, lobortis sodales quam. Maecenas eget fermentum quam. Phasellus gravida justo sollicitudin placerat congue. Integer augue mi, varius et tortor at, sodales semper eros. Vestibulum nec risus nec diam facilisis commodo sed ac leo.
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean in suscipit odio. Sed luctus neque lectus, ut placerat dolor vestibulum tincidunt. Nam sodales mollis metus. Mauris volutpat, ex id hendrerit finibus, arcu sem vulputate libero, et congue metus nunc nec arcu. Nam ut tristique tellus. Etiam mollis faucibus semper. Fusce condimentum cursus eros at sollicitudin. Cras vitae arcu molestie, fringilla neque sed, vestibulum magna. Aliquam cursus vitae sapien ultrices posuere. Sed posuere dolor et accumsan elementum.
					Nullam sed est ligula. Sed in tortor metus. Curabitur in tortor id mi commodo faucibus non eu enim. Nulla facilisi. Cras ut sapien semper, pretium dui vel, volutpat nisl. Nam in ligula in erat dignissim ultricies non pulvinar sapien. Integer sed finibus magna, non facilisis ante. Nunc mollis dolor in posuere malesuada.
					Proin vestibulum elementum augue, vitae luctus velit facilisis fringilla. Vivamus ipsum lectus, luctus a venenatis at, consectetur nec augue. Suspendisse varius in nisl quis consequat. Donec viverra, nisl at venenatis porttitor, turpis tortor viverra felis, ut semper lacus tellus blandit nisi. Sed metus felis, commodo eu turpis et, scelerisque tempor dui. Praesent maximus libero mi. Nam neque lectus, eleifend vitae iaculis et, blandit quis justo. Etiam commodo, erat at semper tincidunt, augue orci sagittis lacus, in dignissim nunc nisl sit amet sem. Aenean ac lorem laoreet, placerat ipsum ac, cursus arcu. Nullam mollis blandit arcu, nec faucibus nisi luctus et. Nunc non magna ullamcorper diam suscipit iaculis. Donec pretium metus non felis aliquam, sit amet tempor eros euismod. Curabitur ullamcorper arcu sem, at maximus turpis luctus id.
					Duis interdum lacus vel pretium pellentesque. Nulla commodo nec lorem eget scelerisque. Sed varius urna in ornare sagittis. Curabitur eu erat sapien. Ut eu tempus felis. In luctus dui augue, at elementum mi commodo nec. Vivamus et hendrerit turpis, sit amet tempus sapien. Suspendisse quis congue est, ac hendrerit odio. Proin nec odio id sapien faucibus egestas. Duis commodo erat eget urna iaculis varius. Integer dui ex, dignissim eu luctus vitae, vulputate eu orci. Praesent sit amet placerat felis, semper mattis lacus.</p>
					
					<p>Fusce lacinia, lectus non auctor laoreet, orci risus tincidunt nisl, in condimentum erat felis quis massa. Maecenas tristique faucibus sem, eu mollis diam ultricies eu. Nulla id urna sit amet urna consectetur eleifend sit amet eu metus. Aliquam erat volutpat. Suspendisse mollis est vel justo placerat, at facilisis mauris porta. Donec et ullamcorper libero. Integer dictum turpis congue metus pharetra, a efficitur sapien ultricies. Phasellus nec risus quis lorem eleifend cursus et faucibus libero. Duis sodales porta ante eget placerat. Aliquam erat volutpat. Donec rutrum rutrum eleifend. Morbi rhoncus hendrerit rhoncus. Vestibulum commodo lorem sollicitudin leo fermentum vulputate. Morbi dapibus magna lacus, sed egestas risus porttitor euismod. Nunc finibus, dui et pulvinar fermentum, mauris orci semper massa, a blandit erat nunc ac felis.
					Suspendisse nibh libero, gravida eget ornare at, pellentesque sit amet ligula. Etiam scelerisque vitae metus efficitur posuere. Aenean feugiat eget diam sit amet elementum. Mauris at sapien nisl. Aenean laoreet mattis eros sit amet molestie. Vestibulum ut ullamcorper leo. Sed ullamcorper eget erat ut laoreet. Duis porta, tellus eu scelerisque faucibus, nisl nulla pellentesque lorem, eu rutrum odio nibh non metus. Etiam sollicitudin purus vel maximus laoreet. Sed sollicitudin felis ultrices nisi laoreet convallis. Mauris eros ipsum, feugiat vitae justo at, blandit mollis felis. Fusce fringilla augue ornare metus condimentum, id rutrum turpis porta. Suspendisse porta tempor fringilla. In hac habitasse platea dictumst.
					Maecenas vitae leo ac ipsum ornare pulvinar vel eget sem. Integer vitae ex consequat, lobortis tortor ac, cursus neque. Curabitur lacinia non dui eleifend cursus. Nam scelerisque turpis lectus, quis porttitor turpis ultricies non. Nullam mi mauris, lobortis sit amet orci in, lobortis venenatis magna. Maecenas consectetur tortor vel nibh porta sodales. Proin feugiat leo nec velit congue, finibus volutpat ante egestas. Nullam interdum enim et neque ultricies, eget mollis diam suscipit. Quisque vel elit lorem. Maecenas eu dictum augue. Quisque vehicula elit a porttitor semper. Proin pretium nunc erat, et dapibus leo rutrum eu. Aenean eget arcu odio. Etiam sagittis ipsum in lobortis bibendum. Aenean mattis posuere nulla aliquet dictum.</p>
					
					<p>Ut luctus vestibulum sagittis. In interdum egestas dui, quis egestas ex ultricies in. Maecenas velit odio, laoreet facilisis nibh a, blandit ornare turpis. Integer eleifend vitae ante et pulvinar. Nulla facilisi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam in consectetur leo, id sollicitudin orci.
					Phasellus ut eros aliquet, mattis ligula ac, sagittis justo. Aenean ac accumsan orci. In pretium cursus dui, a condimentum lectus sagittis at. Proin in dui mollis, congue massa et, placerat massa. Vestibulum egestas tortor id placerat pretium. Nam iaculis id turpis ac suscipit. Pellentesque ultrices sed justo vel pellentesque. Sed rhoncus lectus urna, at suscipit diam malesuada id. Duis mattis feugiat nunc mattis aliquam. In tincidunt ut massa posuere vestibulum. Maecenas condimentum, lacus id viverra vestibulum, elit nisl porta dolor, pharetra placerat mauris felis pulvinar felis. Duis scelerisque viverra nibh, in sodales nibh imperdiet at. Vestibulum eu nisl sit amet purus blandit efficitur nec quis lacus. Nulla sagittis mi odio, sit amet mollis nunc aliquet non. Duis vel odio sit amet magna elementum ultricies.
					Suspendisse vitae ante porttitor, tristique odio at, facilisis ex. Nunc feugiat laoreet rhoncus. Fusce id lectus non velit iaculis auctor vitae vitae quam. Vivamus rhoncus velit vel metus fermentum egestas. Integer commodo ultrices arcu, sed imperdiet est dictum eget. Sed blandit justo sit amet interdum sodales. Mauris sodales neque nec feugiat rutrum. Praesent viverra tempus mauris id semper.
					Suspendisse eu ipsum magna. Pellentesque vulputate ullamcorper metus, eu tempor lorem vestibulum sed. Etiam dui nisl, lobortis id magna non, hendrerit egestas velit. Mauris quis mi eleifend mi molestie consectetur eu non leo. Praesent rutrum ligula nisl, ut placerat justo elementum quis. Quisque in lacinia ipsum. Etiam at porttitor dolor. Fusce pretium leo lectus, vitae dignissim odio malesuada aliquet.
					Aenean ac fringilla metus. Vestibulum dictum enim sit amet elementum convallis. Duis efficitur mi sem, id pretium risus feugiat quis. Pellentesque erat risus, sodales sit amet turpis sed, faucibus gravida purus. Curabitur pellentesque ex in nibh auctor vulputate. Donec lectus ligula, ultrices quis ullamcorper et, dignissim ac nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec non risus ex. Ut in luctus mi. Nullam id dui non urna ullamcorper molestie. Vivamus vehicula faucibus purus quis cursus. Nulla finibus eleifend turpis sollicitudin tempus. Nunc a fringilla metus, ac tempus tellus.</p>
					
					<p>Nulla vitae rhoncus sem. Mauris eget congue ipsum. Integer fermentum neque ac tristique venenatis. Mauris accumsan laoreet dapibus. Morbi malesuada dictum mauris a gravida. Aliquam cursus varius lectus eu luctus. Suspendisse potenti. Nam pretium in ligula quis luctus. Quisque viverra mattis nibh eu ultrices. Praesent sed facilisis urna. Nulla nec vulputate felis. Morbi aliquam mi ut enim tristique, et auctor massa rutrum. Vivamus eget accumsan ligula, a accumsan urna. Praesent gravida, elit at rhoncus hendrerit, ex mauris iaculis diam, eget feugiat nisi dui et arcu. Mauris vitae lacus scelerisque lorem vehicula dapibus vel sed turpis. Vestibulum elementum nec eros accumsan rutrum.
					Phasellus eget diam mi. Curabitur at sagittis dolor. Etiam aliquam lacus id sapien aliquam, ut congue purus ultricies. Quisque ex erat, finibus non turpis et, rutrum facilisis ante. Etiam neque ante, scelerisque quis mauris at, molestie mattis purus. Quisque ut ipsum aliquet lectus scelerisque scelerisque. Donec placerat est odio, a eleifend ligula imperdiet quis. In sodales ex eget malesuada imperdiet.
					Vestibulum malesuada mattis turpis vitae tempus. Praesent quis nulla eget tortor euismod varius et non felis. Fusce vehicula pharetra augue id semper. Nullam tincidunt euismod odio. Integer rhoncus finibus justo. Aliquam at tellus quam. Sed vitae ligula nec orci euismod ornare. Curabitur accumsan arcu at velit ultrices, sit amet gravida turpis mollis. Proin velit libero, tempor pharetra efficitur in, elementum eu sem. Suspendisse laoreet mauris urna, vitae egestas lacus facilisis ac. Suspendisse potenti. Curabitur ac magna arcu.
					Nulla faucibus rhoncus nisi ut commodo. Sed scelerisque, tellus eget cursus tincidunt, mi urna tempor sapien, vel pulvinar sapien tellus eu mi. Ut nunc dolor, egestas sit amet viverra vitae, venenatis eu diam. Integer non sodales nunc, et cursus orci. In hac habitasse platea dictumst. Pellentesque ligula sapien, viverra vel ante varius, convallis ornare elit. Nam faucibus bibendum nisi eu ullamcorper. Curabitur congue pellentesque turpis, id dignissim ante semper vel. Etiam ultricies lacinia consequat. Proin vitae est viverra urna aliquet pretium in ac lectus. Sed iaculis egestas elit at tristique. Mauris suscipit, tortor vel scelerisque eleifend, massa tortor condimentum augue, at tempor sapien ligula nec risus. Aliquam vitae tortor eleifend, pretium nulla vitae, volutpat neque.
					Aliquam erat volutpat. Nam scelerisque luctus nisi. Aenean varius pretium mauris in cursus. Donec molestie, sem id ullamcorper blandit, justo lacus varius purus, at congue urna magna ac metus. Nunc sit amet lorem et odio finibus cursus nec in neque. Vestibulum tortor quam, commodo ac orci in, dapibus pretium erat. Ut pharetra feugiat quam a suscipit.
					Aliquam nec dignissim urna. Nulla a tortor ut diam bibendum tempus. Praesent id urna sit amet ligula tincidunt congue. Donec vestibulum eleifend augue, sed accumsan elit efficitur vel. Vestibulum rutrum lacus vel vulputate dignissim. Integer mollis, nisl a facilisis ultricies, ipsum lectus dapibus felis, quis tincidunt dui mi non quam. Duis ultrices metus ac lacus malesuada, sit amet imperdiet lorem viverra. Curabitur iaculis sagittis nunc dignissim sodales. Cras enim libero, sollicitudin at suscipit at, tincidunt sit amet turpis. Mauris vel nulla ut velit maximus consectetur. Etiam mollis ligula nulla, eget viverra mauris venenatis sit amet.</p>
					
					<p>Mauris neque justo, ornare maximus dui ac, auctor iaculis est. Donec vitae felis in sapien accumsan consequat vel sed nulla. Etiam non nibh gravida, viverra tortor sed, commodo velit. Sed vestibulum justo sed metus mattis cursus. Maecenas interdum, urna a viverra eleifend, elit lorem ultricies ex, nec fringilla augue leo nec eros. Donec bibendum elit ac tincidunt dictum. Morbi eu mi ac purus facilisis eleifend sit amet in eros. Pellentesque aliquet egestas est. Aliquam eu purus enim.
					Cras posuere, dui facilisis venenatis iaculis, est tortor laoreet mauris, vitae cursus nisi magna sit amet felis. Aliquam erat volutpat. Morbi sodales nulla ac massa commodo euismod. Nulla rutrum odio vestibulum elementum viverra. Etiam vel ipsum non mi condimentum vehicula eu ut ligula. Mauris posuere eget sapien in porttitor. Vivamus finibus dignissim ligula et gravida. Ut ultricies vehicula nunc id faucibus. Suspendisse vehicula odio metus. Sed mauris mauris, scelerisque ac arcu eget, malesuada efficitur dolor. Aenean non tortor in neque semper viverra.
					Morbi non diam eget nisi euismod placerat at id mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed bibendum vitae nunc vel placerat. Donec eu lacus venenatis, vestibulum velit nec, commodo tortor. Pellentesque gravida lacinia ligula at iaculis. Maecenas id fringilla nisl. Suspendisse sed purus faucibus, efficitur enim fringilla, varius lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec efficitur ullamcorper auctor. Donec eu turpis ut purus consectetur tempus eu a dolor. Nulla magna ex, tincidunt vel suscipit a, lacinia sit amet erat. Ut rutrum, nisi quis sagittis suscipit, tortor quam suscipit leo, vitae porttitor dui felis ac diam. Sed aliquet aliquet turpis sit amet sagittis. Etiam lacinia odio et lacus congue, eget gravida velit placerat.
					Donec ac quam congue, ullamcorper diam ut, condimentum est. Curabitur malesuada purus magna, et pretium leo commodo a. Nulla dignissim tristique diam. Morbi in placerat orci, in blandit neque. Suspendisse malesuada ac mauris sed posuere. Pellentesque sagittis nisi ipsum, non tempus felis venenatis id. Duis laoreet malesuada enim, a auctor tellus aliquam id. Mauris ut nunc ligula. Cras posuere tellus quis metus semper, id laoreet ipsum rhoncus. Duis et gravida eros. Sed laoreet dapibus libero a finibus. Nam mi purus, egestas non rhoncus sed, pretium eu urna. Morbi fringilla ligula vitae est gravida vulputate. Duis vulputate varius metus, at malesuada risus. In facilisis sodales urna, nec suscipit nulla rhoncus quis.
					Suspendisse potenti. Pellentesque gravida, ex ut pretium dignissim, tortor magna consectetur nisl, et sollicitudin elit libero sed sem. Proin risus purus, mollis vitae ipsum eget, dictum iaculis lacus. Maecenas convallis velit mi, quis lobortis dolor tincidunt eget. Donec turpis libero, sollicitudin nec ultrices sit amet, interdum in nulla. Duis lacinia quam ut orci laoreet consequat. Sed consectetur, nibh non sagittis dapibus, urna quam tincidunt nunc, ut laoreet nulla dolor quis felis. Suspendisse tincidunt libero in tincidunt malesuada. Proin placerat eros a dolor pulvinar pretium. Vestibulum id auctor arcu. Maecenas sodales cursus lorem a faucibus. Phasellus non lacinia nunc. Suspendisse non fringilla leo. Sed ullamcorper est dictum rutrum lacinia. In ut quam nec arcu tempus vestibulum ac a nisl.</p>
					
				</article>
			</section>
			
			<?php include("footer.php"); ?>
			
		</div>		
	</body>
	
</html>